version: '3.9'
services:
    mongo:
        build:
            context: ./docker/mongo
        container_name: ezsol-mongo
        restart: unless-stopped
        environment:
            # Root user for Mongo; required for the init process
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            # App DB name to create
            MONGO_INITDB_DATABASE: ezsol
            # App-level user (created by init script)
            MONGO_APP_USER: ezsol_app
            MONGO_APP_PASSWORD: Zxcvbnm123
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb
        healthcheck:
            test: ['CMD', 'mongosh', '--username', 'root', '--password', 'rootpassword', '--eval', "db.adminCommand('ping')"]
            interval: 60s
            timeout: 5s
            retries: 5
            start_period: 60s

volumes:
    mongo_data:
    mongo_config:
