version: '3.9'
services:
    mongo:
        build:
            context: ./docker/mongo
        container_name: ezsol-mongo
        restart: unless-stopped
        environment:
            # Root user for Mongo; required for the init process
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} # App DB name to create
            MONGO_INITDB_DATABASE: ezsol
            # App-level user (created by init script)
            MONGO_APP_USER: ezsol_app
            # Read from .env (not committed); define MONGO_APP_PASSWORD there
            MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
        ports:
            - '28018:27017'
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb
        healthcheck:
            test: ['CMD', 'mongosh', '--username', 'root', '--password', '${MONGO_INITDB_ROOT_PASSWORD}', '--eval', "db.adminCommand('ping')"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 0s

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ezsol-app
        restart: unless-stopped
        depends_on:
            mongo:
                condition: service_healthy
        ports:
            - '5555:3000'

volumes:
    mongo_data:
    mongo_config:
