// Image path constants - auto-generated by CLI
export type ImagePaths = {
  lightMode: string;
  darkMode: string;
};

// Firebase Storage URLs
export const baseImgUrl = 'https://crypto-images-4545f.web.app/images';
export const baseImgUrlToken = (nameToken: string) => `${baseImgUrl}/token/${nameToken}.png`;
export const baseImgUrlSystem = (nameSystem: string) => `${baseImgUrl}/system/${nameSystem}.png`;
export const baseImgUrlWallet = (nameWallet: string) => `${baseImgUrl}/wallet/${nameWallet}.png`;

// Icon name mapping - auto-generated by CLI
export const iconMap: Record<string, ImagePaths> = {
  // Token icons will be added here
  "ETH": {
    lightMode: baseImgUrlToken("ETH"),
    darkMode: baseImgUrlToken("ETH")
  },
  "SOL": {
    lightMode: baseImgUrlToken("SOL-lightmode"),
    darkMode: baseImgUrlToken("SOL-darkmode")
  },
  "USDC": {
    lightMode: baseImgUrlToken("USDC"),
    darkMode: baseImgUrlToken("USDC")
  },
  "USDT": {
    lightMode: baseImgUrlToken("USDT"),
    darkMode: baseImgUrlToken("USDT")
  },

  // Wallet icons will be added here
  "LazorKit": {
    lightMode: baseImgUrlWallet("LazorKit"),
    darkMode: baseImgUrlWallet("LazorKit")
  }

  // System icons will be added here
};

// Helper function to get icon paths by name
export function getIconPaths(name: string): ImagePaths | null {
  return iconMap[name] || null;
}
