// Image path constants - auto-generated by CLI
export type ImagePaths = {
  lightMode: string;
  darkMode: string;
};

// Firebase Storage URLs
export const baseImgUrl = 'https://firebasestorage.googleapis.com/v0/b/crypto-images';
export const baseImgUrlToken = (nameToken: string) => `${baseImgUrl}-token/o/${nameToken}.png?alt=media`;
export const baseImgUrlSystem = (nameSystem: string) => `${baseImgUrl}-system/o/${nameSystem}.png?alt=media`;
export const baseImgUrlWallet = (nameWallet: string) => `${baseImgUrl}-wallet/o/${nameWallet}.png?alt=media`;

// Icon name mapping - auto-generated by CLI
export const iconMap: Record<string, ImagePaths> = {
  // Token icons will be added here
  "ETH": {
    lightMode: baseImgUrlToken("ETH"),
    darkMode: baseImgUrlToken("ETH")
  },
  "SOL": {
    lightMode: baseImgUrlToken("SOL-lightmode"),
    darkMode: baseImgUrlToken("SOL-darkmode")
  },
  "USDT": {
    lightMode: baseImgUrlToken("USDT"),
    darkMode: baseImgUrlToken("USDT")
  },

  // Wallet icons will be added here
  "LazorKit": {
    lightMode: baseImgUrlWallet("LazorKit"),
    darkMode: baseImgUrlWallet("LazorKit")
  }

  // System icons will be added here
};

// Helper function to get icon paths by name
export function getIconPaths(name: string): ImagePaths | null {
  return iconMap[name] || null;
}
